title: Virendra Kumar
logo: /Asset/dp.png
description: <a href="https://www.linkedin.com/in/virendra-kumar-8b384b136/">Linkedin</a></a>
            <a href="https://orcid.org/0000-0003-0393-4979">ORCID</a>
            <a href="https://scholar.google.com/citations?user=-m_Y9iAAAAAJ&hl=en/">Scholar</a><br>
            <a href="https://www.researchgate.net/profile/Virendra-Kumar-56">ResearchGate</a>
            <a href="https://www.scopus.com/authid/detail.uri?authorId=57564598100">Scopus</a>
            <a href="https://1267virendra.github.io/portfolio/">Github Portfolio</a><br>
            <a href="mailto:virendrakumar1267@gmail.com">Gmail</a>
            <a href="https://www.facebook.com/profile.php?id=100004670146238">Facebook</a><br>
show_downloads: false
theme: jekyll-theme-minimal
